# Generated by Django 2.2.12 on 2020-06-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='links',
            field=models.URLField(blank=True),
        ),
    ]
