# Generated by Django 2.2.12 on 2020-06-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_project_links'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='links',
            new_name='link1',
        ),
        migrations.AddField(
            model_name='project',
            name='link2',
            field=models.URLField(blank=True),
        ),
    ]
