# Generated by Django 2.2.12 on 2020-08-17 10:38

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200624_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='img',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
